Fix SpellMissile IsValidTarget
LeagueSandbox/GameServer pull request #1097
Opened 2021-05-03 20:02 UTC by microsoftv

* SpellMissile:
  * All IsValidTarget implementations changed to properly handle all spell flags.
  * IsValidTarget's team-based checks properly override unit-based checks (NEUTRAL is a special case, as the flag is a unit-based flag).

2021-05-04 10:19 UTC, danil179 requested changes
Some comments. The 2 main issues:
1. This function is already kind of blob, so we want to minimize repeated code as much as we can
2. valid can be returned in some cases, which is preferable.

2021-05-04 10:19 UTC, danil179 commented on GameServerLib/GameObjects/Spell/Missile/SpellCircleMissile.cs
> +                valid = false;
I think you can return `false` here instead of continuing checking (not sure that C# can see this optimization very easily).

2021-05-04 10:19 UTC, danil179 commented on GameServerLib/GameObjects/Spell/Missile/SpellCircleMissile.cs
> +                valid = false;
I think you can return `false` here instead of continuing checking (not sure that C# can see this optimization very easily).

2021-05-04 10:19 UTC, danil179 commented on GameServerLib/GameObjects/Spell/Missile/SpellCircleMissile.cs
> +                valid = false;
I think you can return `false` here instead of continuing checking (not sure that C# can see this optimization very easily).

2021-05-04 10:19 UTC, danil179 commented on GameServerLib/GameObjects/Spell/Missile/SpellCircleMissile.cs
>                  return false;
Why this function not simply call the base class `SpellMissile`? What are the differences?

2021-05-04 10:19 UTC, danil179 commented on GameServerLib/GameObjects/Spell/Missile/SpellMissile.cs
> +                valid = false;
Similar comments about returning false here.

2021-05-05 16:37 UTC, microsoftv commented
> Some comments. The 2 main issues:
> 
> 1. This function is already kind of blob, so we want to minimize repeated code as much as we can
> 2. valid can be returned in some cases, which is preferable.

All resolved.

2021-05-05 17:04 UTC, danil179 approved these changes
Approved.

2021-05-05 17:06 UTC, merged