Stacks_and_Renews fix
LeagueSandbox/GameServer pull request #1132
Opened 2021-06-07 17:41 UTC by cabeca1143

Fixed Stacks_and_Renews triggering ActivateBuff regardless if MaxStacks was reached or not.

2021-06-07 18:02 UTC, danil179 requested changes
It is the stack class responsibility for counting the stacks and verifying things.

2021-06-07 18:02 UTC, danil179 commented on GameServerLib/GameObjects/AttackableUnits/AttackableUnit.cs
> +                    if (ParentBuffs[b.Name].StackCount < ParentBuffs[b.Name].MaxStacks)
I think that you can simply change the `if` to `if (IncementStackCount)` and remove the Increment... from the inside of the `if` block. The Increment part should already stop at MaxStacks and return false when nothing is added.

2021-06-07 19:59 UTC, lzardy commented on GameServerLib/GameObjects/AttackableUnits/AttackableUnit.cs
> +                    if (ParentBuffs[b.Name].StackCount < ParentBuffs[b.Name].MaxStacks)
Make sure to follow the C# guidelines, where all if/else/etc are encased with brackets `{ }` regardless of how small they are.

2021-06-07 20:06 UTC, cabeca1143 commented on GameServerLib/GameObjects/AttackableUnits/AttackableUnit.cs
> +                    if (ParentBuffs[b.Name].StackCount < ParentBuffs[b.Name].MaxStacks)
Oh ok, i just thought it would look better without them.
I'll take a look at the guidelines in a bit.

2021-06-07 20:07 UTC, microsoftv commented on GameServerLib/GameObjects/AttackableUnits/AttackableUnit.cs
> +                    if (ParentBuffs[b.Name].StackCount < ParentBuffs[b.Name].MaxStacks)
https://github.com/LeagueSandbox/GameServer/blob/indev/CONTRIBUTING.md#c-guidelines

2021-06-07 20:07 UTC, cabeca1143 commented on GameServerLib/GameObjects/AttackableUnits/AttackableUnit.cs
> +                    if (ParentBuffs[b.Name].StackCount < ParentBuffs[b.Name].MaxStacks)
Thanks!

2021-06-08 07:01 UTC, danil179 requested changes
You can reduce the number of lines as follows:
```
if(ParentBuffs[b.Name].IncrementStackCount())
{
    ParentBuffs[b.Name].ActivateBuff();
}
```
and deleting the line: `ParentBuffs[b.Name].IncrementStackCount();` that goes after the `if`.

2021-06-08 15:45 UTC, cabeca1143 commented
> You can reduce the number of lines as follows:
> 
> ```
> if(ParentBuffs[b.Name].IncrementStackCount())
> {
>     ParentBuffs[b.Name].ActivateBuff();
> }
> ```
> 
> and deleting the line: `ParentBuffs[b.Name].IncrementStackCount();` that goes after the `if`.

Oh now I see what you mean,

2021-06-08 15:50 UTC, danil179 approved these changes
Approved.

2021-06-08 15:52 UTC, merged