Early introduction of GameModes + Minor fixes
LeagueSandbox/GameServer pull request #1240
Opened 2021-12-03 21:08 UTC by cabeca1143

*Yet Another Map System change
    *Map scripts are now organized in folders, which inside have the `CLASSIC` 
    gamemode, which is the default gamemode.
    
    *Different Gamemodes will be scripted on a different class from the `CLASSIC` 
    gamemode, usually inheriting it. The map to which the Gamemode belongs is 
    definet my it's Namespace.
        *Ex: For Map1 = `MapScripts.Map1`, Map2 = `MapScripts.Map2`....
        
    *MapScripts now contains `GlobalData` and `GameFeatures` to override certain aspects of the game (such as URF overriding 
      Mana costs and CDR cap)
      
    *Changed the template `GameInfo` file to house the new `GameMode` term
    
    *Introduced the URF Gamemode as demonstration
    
*Now Champion Level Ups are done as the match starts, not when they're first loaded.
*Changed Buff packets so they can properly handle buffs that dont have a `SourceSpell`
*Fixed OnKillUnit Event not being published when killing an Unit that doesnt reward gold.

2021-12-03 21:21 UTC, microsoftv commented on GameServerConsole/Settings/GameInfo.json.template
> +  "players": [
Maintain 4 space tab format.

2021-12-03 21:27 UTC, cabeca1143 commented on GameServerConsole/Settings/GameInfo.json.template
> +  "players": [
Resolved

2021-12-03 21:34 UTC, microsoftv requested changes
Few changes needed, looks good otherwise.

2021-12-03 21:34 UTC, microsoftv commented on GameServerConsole/Settings/GameInfo.json.template
> +    "GameMode": "CLASSIC",
Change to lowercase to match formatting.

2021-12-03 21:34 UTC, microsoftv commented on GameServerLib/Config.cs
> +        public IGameFeatures GameFeatures { get; set; }
Change to `private set` and utilize a function for setting.

2021-12-03 21:34 UTC, microsoftv commented on GameServerLib/Config.cs
> +        public bool CooldownsEnabled { get; set; }
Same as above, change to `private set` and utilize a function to set.
```suggestion
        public bool CooldownsEnabled { get; private set; }
        public bool ManaCostsEnabled { get; private set; }
        public bool MinionSpawnsEnabled { get; private set; }
```

2021-12-03 21:34 UTC, microsoftv commented on GameServerLib/Content/CharData.cs
>      // TODO: Add Constants.var files to each Map's Content folder and assign values by reading them, currently this Data is only for Map1 as a placeholder.
Move comment to the new `GlobalData.cs` file.

2021-12-03 21:34 UTC, microsoftv commented on GameServerLib/GameObjects/GlobalData.cs
> +namespace GameServerLib.GameObjects.GlobalData
Move this file to `GameServerLib/Content` and change namespace.
```suggestion
namespace LeagueSandbox.GameServer.Content
```

2021-12-03 21:34 UTC, microsoftv commented on GameServerLib/Maps/MapScriptHandler.cs
> +        public List<IChampion> GetPlayers()
This function is unnecessary as scripts have access to ApiFunctionManager.

2021-12-03 21:34 UTC, microsoftv commented on GameServerCore/Maps/IMapScriptHandler.cs
> +        List<IChampion> GetPlayers();
This function is unnecessary as scripts have access to ApiFunctionManager.

2021-12-04 02:20 UTC, microsoftv approved these changes
Approved.

2021-12-04 02:33 UTC, merged