Resolve #347 -- Game is now pausable
LeagueSandbox/GameServer pull request #353
Opened 2016-12-25 10:09 UTC by FurkanS1821

/pause and /unpause commands fully functional, if 30 minutes have past, the game will auto resume itself.

Refs #347

2016-12-25 11:12 UTC, molenzwiebel commented
The pausing logic should really be moved somewhere else, because currently it is way too easy to accidentally forget the statement and thus having packets that get handled even if the game is paused.

2016-12-25 11:16 UTC, FurkanS1821 commented
@molenzwiebel Packets should be handled, or /unpause wouldn't work

2016-12-25 13:59 UTC, molenzwiebel commented
Well yeah, but it'd still be a cleaner solution to move the unpause packet check to a higher level instead of checking for a paused game in every single packet handler. It's currently way too easy forget the check.

2016-12-25 13:59 UTC, molenzwiebel requested changes
See the comments.

2016-12-26 11:35 UTC, MythicManiac requested changes
Agreed with @molenzwiebel

2016-12-26 16:15 UTC, molenzwiebel approved these changes
Until we have #369 this is the best we can do with regards to checking if a packet needs to be paused. Seems good 👍

2016-12-26 16:34 UTC, MythicManiac commented on GameServerLib/Logic/Packets/PacketHandlers/Handlers/HandleStartGame.cs
> +                            if (_game.IsPaused)
Why is the addition here necessary? Isn't the packet sent in any case further below?

2016-12-26 16:35 UTC, FurkanS1821 commented on GameServerLib/Logic/Packets/PacketHandlers/Handlers/HandleStartGame.cs
> +                            if (_game.IsPaused)
This is sent to the reconnected clients

2016-12-26 16:53 UTC, FurkanS1821 commented
Closing this because it's not pointing to `indev`

2016-12-26 16:53 UTC, closed without merging