Resolve #427 - Update scripts and GameServer from Lua to C Sharp Script
LeagueSandbox/GameServer pull request #428
Opened 2017-01-25 01:06 UTC by MatthewFrench

Updated scripts and GameServer from Lua to C Sharp Script

Refs #427

2017-01-25 02:24 UTC, Heymeelie requested changes

2017-01-25 02:24 UTC, coquicox commented on GameServerLib/Logic/Game.cs
> +            scriptEngine.loadSubdirectoryScripts("Content/Data/LeagueSandbox-Default/");
You should load according to the file config

2017-01-25 04:05 UTC, MatthewFrench commented on GameServerLib/Logic/Game.cs
> +            scriptEngine.loadSubdirectoryScripts("Content/Data/LeagueSandbox-Default/");
Done

2017-01-25 09:45 UTC, FurkanS1821 requested changes
After all that, I don't understand why there are no `onChannelStart` and `onChannelEnd`. They used to exist before this update.

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Bindings.cs
> -            Bind<IScriptEngine>().To<LuaScriptEngine>();
Do not comment unused things, but remove them

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/GameServerLib.csproj
>        <HintPath>..\packages\NLua.1.3.2.1\lib\net45\KeraLua.dll</HintPath>
I think this package is unnecessary, isn't it?

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/API/ApiFunctionManager.cs
>          public static void AddBaseFunctionToLuaScript(IScriptEngine scriptEngine)
Remove instead of commenting

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/Chatbox/Commands/ReloadLuaCommand.cs
> +            /*
I think it would be cool if you get this command working with the name `ReloadScripts`

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/Game.cs
> +            CSharpScriptEngine scriptEngine = CSharpScriptEngine.getInstance();
Bindings.cs
```cs
Bind<CSharpScriptEngine>().To<CSharpScriptEngine>().InSingletonScope();
```
Then to get the only instance from ninject:
```cs
var scriptEngine = Program.ResolveDependency<CSharpScriptEngine>();
```

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Buff.cs
> +        protected CSharpScriptEngine _scriptEngine = CSharpScriptEngine.getInstance();// new LuaScriptEngine();
1. Ninject comment above
2. Remove comment

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Buff.cs
> +            /*
Remove.

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Buff.cs
>          public void LoadLua()
Remove.

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Buff.cs
> +            /*
Remove.

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Buff.cs
> +                    /*
Remove.

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Champion.cs
> +            //LoadLua();
Remove.

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Champion.cs
> +        /*
Remove?

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Champion.cs
> +                /*
Remove.

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Spell.cs
> +        private CSharpScriptEngine _scriptEngine = CSharpScriptEngine.getInstance();
Use Ninject.

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Spell.cs
> +            _scriptEngine = CSharpScriptEngine.getInstance();// new LuaScriptEngine();
Use Ninject. Remove comments.

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Spell.cs
> +            //ReloadLua();
I'm tired of typing lol

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Spell.cs
> +            //_scriptEngine.SetGlobalVariable("castTarget", Target);
I think you know what would be written instead of this.

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Spell.cs
> +        private void RunCast()
That name seems ugly. Something like `RunCastScripts` would be better in my opinion.

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Spell.cs
> +            //if (!_scriptEngine.IsLoaded())
I dont wanna say "remove" anymore. I hope you see all those comments you did.

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/Scripting/IScriptEngineOld.cs
> +    public interface IScriptEngineOld
This class needs removal at all.

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/Logic/Scripting/Lua/LuaScriptEngineOld.cs
> +    public class LuaScriptEngineOld : IScriptEngineOld
^^

2017-01-25 09:45 UTC, FurkanS1821 commented on GameServerLib/packages.config
>  ﻿<?xml version="1.0" encoding="utf-8"?>
NLua should be in this file. Remove its line too.

2017-01-26 05:54 UTC, Heymeelie requested changes

2017-01-26 05:54 UTC, coquicox commented on GameServerLib/Logic/GameObjects/Spell.cs
>          private void RunChannelLua()
Empty function

2017-01-26 05:54 UTC, coquicox commented on GameServerLib/Logic/Chatbox/ChatCommandManager.cs
> +            AddCommand(new ReloadCommand("reloadlua", "", this));
Rename command

2017-01-26 07:20 UTC, Heymeelie approved these changes

2017-01-26 08:48 UTC, molenzwiebel submitted a review, later dismissed
Single commit, remove code instead of commenting it out, and maybe tests.

2017-01-26 09:38 UTC, FurkanS1821 submitted a review, later dismissed

2017-01-26 09:38 UTC, FurkanS1821 commented on GameServerLib/Logic/Chatbox/ChatCommandManager.cs
> +            AddCommand(new ReloadCommand("reloadlua", "", this));
+1

2017-01-26 09:38 UTC, FurkanS1821 commented on GameServerLib/Logic/Chatbox/Commands/ReloadCommand.cs
> +        public override void Execute(Peer peer, bool hasReceivedArguments, string arguments = "")
Will you make this command functional? If not, remove it too

2017-01-26 09:38 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Spell.cs
>          private void RunChannelLua()
+1

2017-01-26 09:38 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Spell.cs
>          public void Teleport(Unit target, float x, float y)
This was added by @Maufeat , he didn't see `ApiFunctionManager.TeleportTo()` so it would be cool if you remove this, and from Ezreal E and Flash.

2017-01-26 09:38 UTC, FurkanS1821 commented on GameServerLib/Logic/Logger.cs
> +
remove whitespace

2017-01-26 09:38 UTC, FurkanS1821 commented on GameServerLib/Logic/Scripting/CSharp/Benchmark.cs
> +                Console.WriteLine("{0} Elapsed(MS) = {1} - FPS: {2}", label, stopwatch.Elapsed.TotalMilliseconds, 1000.0 / stopwatch.Elapsed.TotalMilliseconds);
We have a `Logger`

2017-01-26 09:38 UTC, FurkanS1821 commented on GameServerLib/Logic/Scripting/CSharp/Benchmark.cs
> +                Console.WriteLine(text);
We have a `Logger`

2017-01-26 09:38 UTC, FurkanS1821 commented on GameServerLib/Logic/Scripting/CSharp/CSharpScriptEngine.cs
> +                Console.WriteLine("Loading script: " + scriptLocations[i]);
We have a `Logger`

2017-01-27 02:41 UTC, Heymeelie approved these changes

2017-01-27 16:24 UTC, FurkanS1821 requested changes
I wouldn't approve this with current fucked-up (*by me*) commit history.

2017-01-27 17:13 UTC, FurkanS1821 approved these changes

2017-01-28 07:25 UTC, merged