Resolve #460 - Modify GameScript Format
LeagueSandbox/GameServer pull request #461
Opened 2017-04-11 04:18 UTC by MatthewFrench

Added listeners and changed the GameScript format to be more generic across script types. Preparing for an artificial intelligence script.

2017-04-16 17:30 UTC, molenzwiebel requested changes

2017-04-16 17:30 UTC, molenzwiebel commented on GameServerLib/Logic/API/ApiEventManager.cs
> +    }
Can you unify this in a shared base class?

2017-04-16 17:30 UTC, molenzwiebel commented on GameServerLib/Logic/GameObjects/Champion.cs
>                  return s;
Either replace this, or remove it.

2017-04-16 17:30 UTC, molenzwiebel commented on GameServerLib/Logic/GameObjects/Unit.cs
Same with all of these comments.

2017-04-16 17:30 UTC, molenzwiebel commented on GameServer.userprefs
> +</Properties>
This file should not be added to version control. You might want to add it to .gitignore.

2017-04-16 17:30 UTC, molenzwiebel commented on .gitmodules
> +	branch = spell-refactor-phase-2
This should probably stay as indev, and instead wait for the PR in the other repo to be accepted.

2017-04-18 06:07 UTC, MythicManiac requested changes
Scripting engine seems to be coming along pretty well. 

I do have some change requests though which should be addressed, but overall good work, keep it up 👍

2017-04-18 06:07 UTC, MythicManiac commented on GameServerApp/GameServerApp.csproj
> +    <_CopyCommand>cp -r</_CopyCommand>
Was this change necessary? Using the `-u` flag should result in less changes, as explained below:

```
       -u, --update
              copy only when the SOURCE file is newer than the destination
              file or when the destination file is missing
```

2017-04-18 06:07 UTC, MythicManiac commented on GameServerLib/Logic/API/ApiEventManager.cs
> +    }
All these classes seem to share duplicate code that you could write once and use everywhere :)

2017-04-18 06:07 UTC, MythicManiac commented on GameServerLib/Logic/Content/ContentManager.cs
> +					//Console.WriteLine("Printing: " + directory.Split(new Char[] { '\\', '/' }).Last());
Stray print should be removed

2017-04-18 06:07 UTC, MythicManiac commented on GameServerLib/Logic/GameObjects/Unit.cs
> +        private GameScriptInformation _gameScriptInformation;
While this naming is fine, I think `GameScriptMeta` would be a better name here. No need to swap it but bonus points if you do 👍

2017-04-18 06:07 UTC, MythicManiac commented on GameServerLib/Logic/GameObjects/Unit.cs
> +        public GameScriptBuffController AddBuffGameScript(String buffNamespace, String buffClass, Spell ownerSpell, float removeAfter = -1f, bool isUnique = false, Unit ownerUnit = null)
This is a tad odd naming. `GameScriptBuff` and `BuffGameScript` are both used, IMO should use one or the other in all places, whichever is more consistent with everything else.

2017-04-18 06:07 UTC, MythicManiac commented on GameServerLib/Logic/PreciseTimer.cs
> +				case PlatformID.Unix:
Why has the indentation changed to tabs instead of 4 spaces here? change back please

2017-04-18 06:07 UTC, MythicManiac commented on GameServerLib/Logic/GameObjects/Unit.cs
I'm 50/50 with this. While usually comments shouldn't be in the codebase, since this is a WIP replacement it could make sense to keep them around instead of digging commit history.

Anyway, if you could implement a dummy event/method call with a `//TODO`flag + create an issue for those, that would be a better approach

2017-04-18 06:07 UTC, MythicManiac commented on GameServerLib/Logic/Scripting/Engine/GameScriptBuffController.cs
> +        Unit _unit, _target;
Could the `_unit` variable be renamed to something more clear? Is it the owner/creator of the buff or something else? Probably should be renamed `_owner`

2017-04-18 06:07 UTC, MythicManiac commented on GameServerLib/Logic/Scripting/Engine/GameScriptEngine.cs
> +			return _scriptingEngine.LoadSubdirectoryScripts(Path.Combine("Content", "Data", gameMode));
This has tab indentation instead of spaces as well, please fix :)

2017-04-18 06:13 UTC, MatthewFrench commented on GameServerApp/GameServerApp.csproj
> +    <_CopyCommand>cp -r</_CopyCommand>
Mac wouldn't work with the -u there. Something to do with difference in commands across Unix. There might be a better way to fix it.

2018-08-12 16:32 UTC, closed without merging