Resolve #438 -- aimesh_ngrid update
LeagueSandbox/GameServer pull request #501
Opened 2017-08-24 15:27 UTC by FurkanS1821

Description required is in the issue.

Refs #438

2017-08-24 15:37 UTC, moonshadow565 commented on GameServerLib/Logic/Maps/Map.cs
> +            var dict = new Dictionary<int, Type>
Is this really necessary because i was thinking of loading ``MapGameScript`` from content folder?

2017-08-24 15:41 UTC, FurkanS1821 commented on GameServerLib/Logic/Maps/Map.cs
> +            var dict = new Dictionary<int, Type>
I thought about that too but then chose to implement it in another PR.

2017-08-24 15:42 UTC, moonshadow565 commented on GameServerLib/Logic/Maps/Map.cs
> +            var dict = new Dictionary<int, Type>
I know, there is too much things generic things going in ``SummonersRift`` now so i was doubting the need to support so many maps at all for now...

2017-08-28 18:05 UTC, MythicManiac requested changes
Good work! Nice to see someone hooking us up with some proper pathfinding!

There are a few things that I'd like to see addressed, but overall looking very good.

Keep up the good work!

2017-08-28 18:05 UTC, MythicManiac commented on GameServerLib/Logic/GameObjects/Other/MovementVector.cs
> +            this.x = FormatCoordinate(x, _game.Map.NavGrid.MapHeight / 2);
The center vector is a constant so that could be cached to a public readonly vector in the NavGrid.

2017-08-28 18:05 UTC, MythicManiac commented on GameServerLib/Logic/Maps/SummonersRift.cs
> +            var toRet = "";
What is this a shorthand of? `toReturn`? Could a more clear naming be used, e.g. `result`?

2017-08-28 18:05 UTC, MythicManiac commented on GameServerLib/Logic/Maps/SummonersRift.cs
> +            switch (type)
These switches could also be implemented as dictionaries, but I don't think we're going to have new minion types anytime soon so I suppose this is fine for now. Change if you want but feel free to leave as is.

2017-08-28 18:28 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Other/MovementVector.cs
> +            this.x = FormatCoordinate(x, _game.Map.NavGrid.MapHeight / 2);
I cannot make a readonly variable because `NavGrid` has no constructors. But I will make one.

2017-08-29 07:45 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Other/MovementVector.cs
> -            this.y = FormatCoordinate(y, _game.Map.NavGrid.MapWidth / 2);
Before you ask, I also don't know why these two are inverted, I kept them inverted.

2017-08-30 17:59 UTC, MythicManiac approved these changes
Looks good, feel free to squash merge in proper commit format 👍 

Good work!

2017-08-30 18:05 UTC, merged