League of Memories: New changes report
LeagueSandbox/GameServer pull request #558
Opened 2018-04-27 15:01 UTC by Deudly

* Added the necessary functions for passives to update
* Changing the way Recall is handeled

2018-06-04 13:14 UTC, FurkanS1821 requested changes

2018-06-04 13:14 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/AttackableUnits/AI/Champion.cs
> +                Spells[(byte)(i + 6)] = new Spell(this, "", (byte)(i + 6));
There's exactly what you would want to use as an empty spell: `BaseSpell`.
Riot uses these for non-champion objects, and I believe going that way is better than using an empty string.

2018-06-04 13:14 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/AttackableUnits/AI/Champion.cs
> +                return new Spell(this, "", slot);
There's exactly what you would want to use as an empty spell: BaseSpell.
Riot uses these for non-champion objects, and I believe going that way is better than using an empty string.

2018-06-04 13:14 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/AttackableUnits/AI/Champion.cs
> +			if (this.isMovementUpdated()) {
indentation

2018-06-04 13:14 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/AttackableUnits/AI/Champion.cs
> +			var spawnPos = GetRespawnPosition();
indentation

2018-06-04 13:14 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/AttackableUnits/AI/Champion.cs
> +			if (this.isMovementUpdated()) {
\+ bracket should be one line below

2018-06-04 13:14 UTC, FurkanS1821 commented on GameServerLib/Logic/GameObjects/Spells/Spell.cs
> +            if (spellName != "")
`!spellName.Equals("")`, or even better: `!string.IsNullOrEmpty(spellName)`

here is why: https://stackoverflow.com/a/814881

2018-06-09 12:33 UTC, piorrro33 commented
Also see my comments on #563

2018-06-27 14:56 UTC, HarmfulBreeze requested changes
Fix conflicts and the issues Furkan mentioned.
Also please give actual names to your commits, not just "commit" or "update"
Besides that, not much else to say

2018-07-19 21:10 UTC, HarmfulBreeze reviewed
Also too many changes! God!

2018-07-19 21:10 UTC, piorrro33 commented on .travis.yml
> -    - sudo apt-get install nuget
Are you sure it still works without installing the nuget package?

2018-08-26 09:07 UTC, Deudly commented
Closing this PR since it's useless

2018-08-26 09:07 UTC, closed without merging