Update junglespawn command
LeagueSandbox/GameServer pull request #835
Opened 2019-06-08 15:58 UTC by xxx3456789

+ Feature :
!junglespawn 1(Only normal camps) / 2 (Only Epic monsters) / 3 (normal + Epic)
- Issues :
They don't have AI, like woods standing there.

2019-07-04 22:30 UTC, danil179 requested changes
Too much hardcoded things. That should be generated from some file and without using hardcoding.

2019-09-08 19:55 UTC, FurkanS1821 requested changes
I don't know if adding a command to spawn mindless jungle monsters is a step forward but let's go

2019-09-08 19:55 UTC, FurkanS1821 commented on GameServerLib/Chatbox/Commands/JunglespawnCommand.cs
> +        private void BlueTeam01()
These function names don't really look self-explanatory, can we change them with something like `Spawn(Blue|Red)(Left|Right)Jungle` and `Spawn(Dragon|Baron)` please?

2019-09-08 19:55 UTC, FurkanS1821 commented on GameServerLib/Chatbox/Commands/JunglespawnCommand.cs
> +            var BlueWolfBig = new Monster(
local variables should be `likeThis`

2019-09-08 19:55 UTC, FurkanS1821 commented on GameServerLib/Chatbox/Commands/JunglespawnCommand.cs
> +            //_logger.Warn($"{ChatCommandManager.CommandStarterCharacter}{Command} command not implemented");
Please remove unused code instead of commenting it out.

2022-02-21 06:28 UTC, microsoftv commented
This PR has been superseded by #1269

2022-02-21 06:28 UTC, closed without merging