Refractoring the content loading system
LeagueSandbox/GameServer pull request #844
Opened 2019-07-22 17:32 UTC by abosma

Currently data is loaded immediately from /Content/PackageName, this was now changed to follow the structure on the league sandbox website: [(given package structure)](https://cdn.discordapp.com/attachments/261986574487519232/602913723945844745/unknown.png). Items are now also not hard-coded but checks inside of the given datapackage in GameMode.json.

Next thing is see if it's better to merge gamemode and data or to keep it like this, then do whatever is decided.

2019-07-22 20:25 UTC, abosma commented
I implemented a recursive package loading system. GameMode is not used at all anymore, every package must now contain a packageInfo.json with a structure like: `{ "dependencies": [ "Self-PackageName", "Other-PackageName" ] }`. Every other packages' dependencies will be loaded in as well.

GameInfo.json does not have a gameMode line anymore under game but now a dataPackage line with the initial loaded data package as value.

2019-07-22 20:43 UTC, abosma commented
Removed the need for Self-PackageName in packageInfo.json, the new json format is: `{ "dependencies": [ "Other-PackageName" ] }`

2019-07-23 11:38 UTC, abosma commented
Data is now again loaded from /Content/PackageName, scripts that frequently get edited (Buffs and Champions) have now been moved to LeagueSandbox-Scripts. LeagueSandbox-Default now has a dependency on that folder.

Other than that some error handling was also added in case a package does not containt packageInfo.json, it will now skip the dependencies from that package but still load it in.

2019-07-24 15:02 UTC, abosma commented
Loading scripts and buffs from another package does not work well yet, making a more robust version of content loading.

2019-07-24 17:17 UTC, abosma commented
While currently loading in multiple packages and dependency chaining works, it might be better to look at creating a nicer version of the current content loading system. Maybe create package classes that handle loading in themselves.

2019-07-25 13:56 UTC, abosma commented
Package class added. This is created per given PackageName in GameInfo and dependencies inside of this package. This package loads itself in, instead of ContentManager loading this data in. Loaded in content is now no longer in ContentManager but split up per Package, ContentManager holds these packages.

Things that are not yet loaded in by packages themselves are: Map spawns and NavGrid.

2019-07-25 15:08 UTC, abosma commented
MapSpawns and NavGrids now get loaded in through the package class. The spawns and navgrid that is chosen is currently based on load order of the packages starting with the given package in GameInfo.json.

2019-07-25 20:04 UTC, abosma commented
The added commands are !loadpackage {packagename} and !showpackages

2019-07-27 08:03 UTC, microsoftv commented on Content/LeagueSandbox-Scripts/Buffs/NidaleeTransformedQBuff/NidaleeTransformedQBuff.cs
> +namespace NidaleeTransformedQBuff
Unnecessary addition.

2019-07-27 08:10 UTC, microsoftv commented on Content/LeagueSandbox-Scripts/Buffs/NidaleeEBuff/NidaleeEBuff.cs
> +namespace NidaleeEBuff
Unnecessary, same as WBuff.

2019-07-27 08:14 UTC, microsoftv commented on Content/LeagueSandbox-Scripts/Champions/Nidalee/E.cs
> +    class PrimalSurge : IGameScript
Unnecessary, same as NidaleeE/WBuff.

2019-07-27 08:15 UTC, microsoftv commented on Content/LeagueSandbox-Scripts/Champions/Nidalee/R.cs
> +    class AspectOfTheCougar : IGameScript
Unnecessary, same as PrimalSurge and NidaleeE/WBuff.

2019-07-27 08:16 UTC, microsoftv commented on Content/LeagueSandbox-Scripts/Champions/Nidalee/TransformedE.cs
> +    class Swipe : IGameScript
Unnecessary, same as the other Nidalee additions

2019-07-27 08:16 UTC, microsoftv commented on Content/LeagueSandbox-Scripts/Champions/Nidalee/TransformedQ.cs
> +    class Takedown : IGameScript
Unnecessary, same as the other Nidalee additions.

2019-07-27 08:16 UTC, microsoftv commented on Content/LeagueSandbox-Scripts/Champions/Nidalee/TransformedW.cs
> +    class Pounce : IGameScript
Unnecessary, same as the other Nidalee additions.

2019-07-27 08:16 UTC, microsoftv commented on Content/LeagueSandbox-Scripts/Champions/Nidalee/W.cs
> +    class Bushwhack : IGameScript
Unnecessary, same as the other Nidalee additions.

2019-07-27 08:31 UTC, microsoftv commented on Content/LeagueSandbox-Scripts/LeagueSandbox-Scripts.csproj
> +    <Compile Include="Champions\Nidalee\E.cs" />
Remove unnecessaries from scripts project.

2019-07-27 08:38 UTC, microsoftv commented on GameServerCore/Domain/ICharData.cs
> +    public interface ICharData
Not sure how to feel about a duplicate CharData lying around in Core/Domain.

2019-07-27 08:44 UTC, microsoftv commented on GameServerLib/Config.cs
> +            ContentManager = ContentManager.LoadDataPackage(game, GameConfig.DataPackage, ContentPath);
May want to re-add some form of distinction between packages and modes (for another PR most likely).

2019-07-27 08:51 UTC, microsoftv commented on GameServerLib/Content/Package.cs
> +        private readonly Dictionary<string, CharData> _charData = new Dictionary<string, CharData>();
Use ICharData.
```suggestion
        private readonly Dictionary<string, ICharData> _charData = new Dictionary<string, ICharData>();
```

2019-07-27 09:00 UTC, microsoftv commented on GameServerLib/GameObjects/AttackableUnits/AI/ObjAIBase.cs
> +            CharData = (CharData) _game.Config.ContentManager.GetCharData(Model);
Use ICharData.
```suggestion
            CharData = (ICharData) _game.Config.ContentManager.GetCharData(Model);
```
**Requires**:
```
        public ICharData CharData { get; } // line 38 ObjAIBase.cs
```
```
        public void LoadStats(ICharData charData) // line 109 Stats.cs
```

2019-07-27 09:03 UTC, lzardy requested changes
Apply changes based on my comments (besides those that are stated as suggestions).

2019-07-27 09:19 UTC, abosma commented
Implemented changes requested

2019-07-27 09:20 UTC, lzardy approved these changes
Click resolve on all comments and you should be good to go.

2019-07-27 09:29 UTC, microsoftv commented
Seems like you'll need to rebase to get the checks to run correctly.

2019-07-27 10:21 UTC, abosma commented
Rebased and commited the merge with the latest auto attack change.

2019-07-28 09:48 UTC, abosma commented
Removed LeagueSandbox-Scripts from PR, going to make another pull request for adding LeagueSandbox-Scripts and discuss there.

2019-07-31 11:17 UTC, moonshadow565 approved these changes

2019-07-31 11:17 UTC, merged