Improve #822 - Adding DashSpeed to ObjAiBase
LeagueSandbox/GameServer pull request #920
Opened 2019-11-28 13:28 UTC by abosma

Improved the state of dashing by implementing DashSpeed to ObjAiBase and returning it if the character is currently dashing.

2019-11-28 13:40 UTC, cntseesharp commented
Champion can have several dashes (Lee Sin, J4, Kha E range difference, Riven), thus dash speed will be different

2019-12-29 03:45 UTC, danil179 requested changes
One comment.

2019-12-29 03:45 UTC, danil179 commented on GameServerLib/GameObjects/AttackableUnits/AI/ObjAIBase.cs
> +        public float DashSpeed { get; set; }
I think we can start with at least protected set and see if "public" is really needed.

2020-01-09 18:59 UTC, danil179 approved these changes
Will open issue about protected vs public.

2020-01-09 19:00 UTC, merged