Fix Bugs Introduced by #845 and QuadTree
LeagueSandbox/GameServer pull request #937
Opened 2020-01-08 02:38 UTC by microsoftv

1. Fixes vision issues
2. Fixes collision issues, specifically ones regarding buildings

2020-01-08 02:40 UTC, microsoftv commented
I'd like to note that QuadTree seems to be a volatile addition in its current state.

2020-01-08 11:58 UTC, compsi627 commented on GameServerLib/Content/NavGrid.cs
> -            var rayDist = Math.Sqrt(CastRaySqr(a.GetPosition(), b.GetPosition()));
Why is that needed? Also, I think that will break the lines come after.

2020-01-08 11:59 UTC, danil179 commented on GameServerLib/Content/NavGrid.cs
> -            var rayDist = Math.Sqrt(CastRaySqr(a.GetPosition(), b.GetPosition()));
Why is that needed? Also, I think that will break the lines come after.

2020-01-08 12:00 UTC, danil179 commented
> 
> 
> I'd like to note that QuadTree seems to be a volatile addition in its current state.

I'm not sure. The main problem is that the current lib of this QuadTree seems to be very unreliable, but widely used. I don't know if we do something wrong, or it's just the lib.

2020-01-09 02:38 UTC, danil179 requested changes
Apart from one comment, it looks good.

2020-01-09 02:38 UTC, danil179 commented on GameServerLib/Content/NavGrid.cs
> +                return (rayDist * rayDist) < (b.GetPosition() - a.GetPosition()).SqrLength();
Take this line out of the if.

2020-01-09 02:38 UTC, danil179 commented on GameServerLib/Content/NavGrid.cs
> +                return (rayDist * rayDist) < (b.GetPosition() - a.GetPosition()).SqrLength();
And this. (Delete one of them)

2020-01-09 02:47 UTC, danil179 approved these changes
Approved.

2020-01-09 02:52 UTC, merged