Cleanup LaneMinion
LeagueSandbox/GameServer pull request #965
Opened 2020-03-23 22:03 UTC by microsoftv

Removes loop-back issues and removes functions which hide parent functions.
Gives a big boost to performance even though this is such a small change.
If there are any other concerns when looking at Minion.cs or LaneMinion.cs, please address them at your leisure as these parts of LS will likely be ignored for quite a while, while bigger, more baseline issues are addressed.

2020-03-24 13:15 UTC, danil179 requested changes
More cleaning needed.

2020-03-24 13:15 UTC, danil179 commented on GameServerLib/GameObjects/AttackableUnits/AI/Minion.cs
> +                else if (this is ILaneMinion lm)
It doesn't look clean to me. Minion should have no knowledge about LaneMinion (I think this implicated from Liskov substitution principle). In this case you want a function like `AIMove` that will do the walk to destination in LaneMinion but will do other things in Minion class.

I think that you can put:
```
if (ScanForTargets()) // returns true if we have a target
                {
                    if (!RecalculateAttackPosition())
                    {
                        KeepFocusingTarget(); // attack/follow target
                    }
                }
```
in a function (call it `AIMove` or something like that in Minion class, and then override it in LaneMinion to be:
```
base.AIMove()
lm.WalkToDestination(); // walk to destination (or target)
```

2020-03-25 06:45 UTC, MatthewFrench commented on GameServerLib/GameObjects/AttackableUnits/AI/LaneMinion.cs
> +            IsLaneMinion = true;
In a future ticket, we could probably turn this into a base function that returns a static true or false and have LaneMinion override the function to return true. Then we wouldn't need a variable.

2020-03-25 06:49 UTC, MatthewFrench approved these changes

2020-03-25 09:59 UTC, danil179 approved these changes
Approved. You need to rebase in order to rebuild (change the commit message).

2020-03-25 19:29 UTC, merged